#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_KHR_shader_subgroup_basic : enable

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, set = 0) uniform sampler2D depthInput;
layout(r32f, binding = 0, set = 1) uniform writeonly image2D outputImage;

layout(std140, binding = 0, set = 2) uniform Test {
    vec2 blurDir;
};

const int numWeights = 8;

highp float linearizeDepth(in highp float d)
{
	const highp float f = 1000.0f;
	const highp float n = 0.1f;
	return (n * f) / (f + d * (n - f));
}

void main (void)
{
    vec2 coord = vec2(gl_GlobalInvocationID.xy);
    highp float result = 0.0;
    highp float weights = 0.0;

    highp float z_i = texture(depthInput, coord).x;

    if (z_i == 1.0)
    {
        imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(1, 0, 0, 0));
        return;
    }


    highp float z_i_linear = linearizeDepth(z_i);

    result = 0.0;

    const float delta = 0.99;
    const float mu = 0.01f;

    const float falloff = 0.01f;

    for(int dx = -numWeights; dx < numWeights; dx++)
    {
        for(int dy = -numWeights; dy < numWeights; dy++)
        {
            highp float z_j = texture(depthInput, coord + ivec2(dx,dy)).x;
            highp float z_j_linear = linearizeDepth(z_j);

            highp float z_k = texture(depthInput, coord - ivec2(dx,dy)).x;
            highp float z_k_linear = linearizeDepth(z_k);


            highp float r_1 = (z_i_linear - z_j_linear) * falloff;
            highp float w_1 = exp(-r_1 * r_1);

            highp float r_2 = (z_i_linear - z_k_linear) * falloff;
            highp float w_2 = exp(-r_2 * r_2);

            vec2 d = vec2(dx, dy) / vec2(numWeights, numWeights);
            highp float dist = length(d);
            highp float w_ij = exp(-dist * dist);

            weights += w_ij * w_1 + w_ij * w_2;
            result += w_ij * w_1 * z_j + w_ij * w_2 * z_k;


            /*


            if (!(z_j == 1.0 || z_k == 1.0 || z_j_linear > z_i_linear + delta || z_k_linear > z_i_linear + delta))
            {
                vec2 d = vec2(dx, dy) / vec2(numWeights, numWeights);
                float dist = length(d);
                float w_ij = exp(-dist * dist);

                float f_ij = z_j;
                if (z_j > z_i - delta)
                    f_ij = z_i - mu;

                result += w_ij * f_ij;

                weights += w_ij;
            }

            */

        }
    }
    result /= weights;

    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(result, 0, 0, 0));
}
