#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_KHR_shader_subgroup_basic : enable

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, set = 0) uniform sampler2D depthInput;
layout(r32f, binding = 0, set = 1) uniform writeonly image2D outputImage;

layout(std140, binding = 0, set = 2) uniform Test {
    vec2 blurDir;
};

const uint numWeights = 8;

float linearizeDepth(in float d)
{
	const float f = 1000.0f;
	const float n = 1.0f;
	return (2 * n) / (f + n - d * (f - n));
}

void main (void)
{
    vec2 coord = vec2(gl_GlobalInvocationID.xy);
    float result = 0.0;

//    float depth = texture(depthInput, coord).x;

    for(uint i = 0; i < numWeights; i++) {
        float depth = texture(depthInput, coord + ivec2(i,0)).x;
        result += linearizeDepth(depth) / float(numWeights);
    }
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(result, 0, 0, 0));
}
