#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_KHR_shader_subgroup_basic : enable

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, set = 0) uniform sampler2D depthInput;
layout(rgba8, binding = 0, set = 1) uniform writeonly image2D outputImage;

layout(binding = 0, std140, set = 2) uniform GlobalUniformBuffer {
    highp mat4 mat;
    highp mat4 invviewmat;
    highp mat4 viewmat;
    highp mat4 invprojmat;
    highp mat4 projmat;
    highp mat3 viewRot;
} ubo;

highp float linearizeDepth(in highp float d)
{
	const highp float f = 1000.0f;
	const highp float n = 0.1f;
	return (n * f) / (f + d * (n - f));
}

// ((-(f+n) * z - 2fn) / (f - n)) / -z

// ((f+n) - 2fn) / (f - n)
// () / (f - n)

// (-(f+n) * z - 2fn) / (f - n)

highp vec3 getpos (in highp vec3 p)
{
    highp vec4 clip = vec4 (p.xy * 2 - 1, p.z, 1);
    highp vec4 view = ubo.invprojmat * clip;
    view /= view.w;

    return view.xyz;
    /*highp vec4 world = ubo.invviewmat * view;
    world.xyz /= world.w;
    return world.xyz;*/
}

void main (void)
{
    vec2 coord = vec2(gl_GlobalInvocationID.xy);
    const float width = 1024.0f; // TODO: make parameters
    const float height = 1024.0f; // TODO: make parameters
    vec2 normcoords = vec2(gl_GlobalInvocationID.xy) / vec2(width,height);
    float depth = texture(depthInput, coord).x;

    if (depth == 1.0)
    {
        imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(0.1,0.1,0.1,1.0));
        return;
    }

    vec3 pos = getpos(vec3(normcoords, depth));

    vec2 normcoords_x = normcoords + vec2(1.0f / width, 0.0f);
    vec3 ddx = getpos(vec3(normcoords_x, texture(depthInput, coord + vec2(1.0f, 0.0f)).x)) - pos;
    vec2 normcoords_x2 = normcoords - vec2(1.0f / width, 0.0f);
    vec3 ddx2 = pos - getpos(vec3(normcoords_x2, texture(depthInput, coord - vec2(1.0f, 0.0f)).x));
	if (abs (ddx.z) > abs (ddx2.z)) ddx = ddx2;

    vec2 normcoords_y = normcoords + vec2(0.0f, 1.0f / height);
    vec3 ddy = getpos(vec3(normcoords_y, texture(depthInput, coord + vec2(0.0f, 1.0f)).x)) - pos;
    vec2 normcoords_y2 = normcoords - vec2(0.0f, 1.0f / height);
    vec3 ddy2 = pos - getpos(vec3(normcoords_y2, texture(depthInput, coord - vec2(0.0f, 1.0f)).x));
	if (abs (ddy.z) < abs (ddy2.z)) ddy = ddy2;

    vec3 normal = normalize(cross(ddx, ddy));

    vec3 lightdir = normalize(vec3(-1, 0, -1));

    float NdotL = max(dot(lightdir, normal) * 0.5 + 0.5, 0);

    vec4 fOut = vec4(0.005*NdotL, 0.4*NdotL, NdotL, 0);

    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), fOut);
}
