#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_KHR_shader_subgroup_basic : enable

#include "../../common.comp"

layout (local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

struct DistanceConstraint {
    uint index_i;
    uint index_j;
    float distance;
    float alpha; // stiffness
    vec4 aux;
};

layout(std430, binding = 0, set = 0) readonly buffer DistanceConstraintBuffer
{
    DistanceConstraint constraints[];
};

layout(std430, binding = 0, set = 1) buffer LambdaBuffer
{
    float lambdas[];
};

layout(std430, binding = 0, set = 2) buffer Particles
{
    ParticleData particles[];
};

layout(std430, binding = 1, set = 2) readonly buffer ParticlesOrig
{
    ParticleData particlesOrig[];
};

layout (constant_id = 9) const uint numConstraints = 0;

layout(push_constant) uniform constants {
    float timestep;
};

void main(void)
{
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= numConstraints)
        return;
    DistanceConstraint constraint = constraints[gid];
    ParticleData particle_i = particles[constraint.index_i];
    vec3 particle_j = constraint.aux.xyz;//particles[constraint.index_j].position;

    vec3 v = particle_i.position - particlesOrig[constraint.index_i].position;

    vec3 dist_ij = particle_i.position - particle_j;
    float normsquared = dot(dist_ij, dist_ij);
    float norm = sqrt(normsquared);
    float distsquared = constraint.distance*constraint.distance;
    float dist = constraint.distance;
    float violation = norm - dist;
    const float forceConstant = 1.0;
    vec3 grad_C_k = 2. * forceConstant * violation / norm * dist_ij;
    float gradLength = length(grad_C_k);
    grad_C_k = normalize(grad_C_k) * clamp(gradLength, 0, 100);
    float inverseMassFactor = 1.0 / GetMassForType(particle_i.type); // TODO
    float deltaT = timestep;
    float alphaSquiggly = constraint.alpha / (deltaT*deltaT);
    //float deltaLambda =(-forceConstant*violation*violation - alphaSquiggly * lambdas[gid]) / (dot(grad_C_k, grad_C_k) * inverseMassFactor + alphaSquiggly);
    float beta = 1.0;
    float gamma = alphaSquiggly * deltaT * beta;
    float deltaLambda =(-forceConstant*violation*violation - alphaSquiggly * lambdas[gid] - gamma * dot(grad_C_k, v)) / ((1 + gamma) * dot(grad_C_k, grad_C_k) * inverseMassFactor + alphaSquiggly);
    lambdas[gid] += deltaLambda;
    particles[constraint.index_i].aux = floatBitsToUint(min(abs(lambdas[gid]) * 10000000.0, 1.0));

    vec3 deltax = inverseMassFactor * grad_C_k * deltaLambda;
    // TODO: atomic
    particles[constraint.index_i].position += deltax;
}
