#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_KHR_shader_subgroup_basic : enable

layout (local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0, set = 1) readonly buffer Keys
{
    uint keys[];
};

layout(std430, binding = 1, set = 1) writeonly buffer Result
{
    uint result[];
};

uint GetPermutation(uint id);

void main()
{
    result[GetPermutation(gl_GlobalInvocationID.x)] = keys[gl_GlobalInvocationID.x];
}
