#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_atomic_float : enable

#include "../../common.comp"

layout (local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

struct PositionConstraint {
    vec3 position;
    uint index_i;
    float distance;
    float alpha;
    float forceConstant;
    float beta;
};

layout(std430, binding = 0, set = 0) readonly buffer PositionConstraintBuffer
{
    PositionConstraint constraints[];
};

layout(std430, binding = 0, set = 1) buffer LambdaBuffer
{
    float lambdas[];
};

layout(std430, binding = 0, set = 2) buffer Particles
{
    ParticleData particles[];
};

layout(std430, binding = 1, set = 2) readonly buffer ParticlesOrig
{
    ParticleData particlesOrig[];
};

layout (constant_id = 9) const uint numConstraints = 0;

layout(push_constant) uniform constants {
    float timestep;
    float forceConstantFactor;
    float alphaFactor;
    float betaFactor;
};

void main(void)
{
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= numConstraints)
        return;
    PositionConstraint constraint = constraints[gid];
    ParticleData particle_i = particles[constraint.index_i];
    vec3 target_position = constraint.position;

    vec3 v_i = particle_i.position - particlesOrig[constraint.index_i].position;

    vec3 dist_ij = particle_i.position - target_position;
    float normsquared = dot(dist_ij, dist_ij);
    float norm = sqrt(normsquared);
    float violation = norm;
    float forceConstant = forceConstantFactor * constraint.forceConstant;
    vec3 grad_C_k = 2. * forceConstant * violation / norm * dist_ij;
    //float gradLength = length(grad_C_k);
    //grad_C_k = normalize(grad_C_k) * clamp(gradLength, 0, 100);
    float inverseMassFactor_i = 1.0 / GetMassForType(particle_i.type);
    float deltaT = timestep;
    float alphaSquiggly = alphaFactor * constraint.alpha / (deltaT*deltaT);
    //float deltaLambda =(-forceConstant*violation*violation - alphaSquiggly * lambdas[gid]) / (dot(grad_C_k, grad_C_k) * inverseMassFactor + alphaSquiggly);
    float beta = betaFactor * constraint.beta; // 0.01
    float gamma = alphaSquiggly * deltaT * beta;
    float deltaLambda = (-forceConstant*violation*violation - alphaSquiggly * lambdas[gid] - gamma * dot(grad_C_k, v_i)) / ((1 + gamma) * dot(grad_C_k, grad_C_k) * inverseMassFactor_i + alphaSquiggly);
    lambdas[gid] += deltaLambda;

    vec3 deltax = grad_C_k * deltaLambda;
    // TODO: atomic
    /*particles[constraint.index_j].position -= inverseMassFactor_j * deltax;
    particles[constraint.index_i].position -= inverseMassFactor_i * deltax;*/
    // TODO: this should really not write into the same buffer, but ping-pong into a new one per iteration.
    atomicAdd(particles[constraint.index_i].position.x, inverseMassFactor_i * deltax.x);
    atomicAdd(particles[constraint.index_i].position.y, inverseMassFactor_i * deltax.y);
    atomicAdd(particles[constraint.index_i].position.z, inverseMassFactor_i * deltax.z);
}
