#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_KHR_shader_subgroup_basic : enable

layout (local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

const uint BLOCKSIZE = gl_WorkGroupSize.x;

layout(std430, binding = 0) buffer Data
{
    uint data[];
};

layout(std430, binding = 1) readonly buffer BlockSums
{
    uint blocksums[];
};


void main()
{
    data[gl_GlobalInvocationID.x] += blocksums[gl_WorkGroupID.x];
}
