/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fub_pbf_impl_JNIPBF */

#ifndef _Included_de_fub_pbf_impl_JNIPBF
#define _Included_de_fub_pbf_impl_JNIPBF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _resized
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1resized
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1init
  (JNIEnv *, jobject);

/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _display
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1display
  (JNIEnv *, jobject);

/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1start
  (JNIEnv *, jobject);

/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1stop
  (JNIEnv *, jobject);

/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _zoom
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1zoom
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _move
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1move
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _rotate
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1rotate
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     de_fub_pbf_impl_JNIPBF
 * Method:    _dispose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_impl_JNIPBF__1dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
