/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fub_pbf_JNIPBFWrapper */

#ifndef _Included_de_fub_pbf_JNIPBFWrapper
#define _Included_de_fub_pbf_JNIPBFWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    _resized
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_JNIPBFWrapper__1resized
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    _init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_JNIPBFWrapper__1init
  (JNIEnv *, jobject);

/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    _display
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_JNIPBFWrapper__1display
  (JNIEnv *, jobject);

/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    _start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_JNIPBFWrapper__1start
  (JNIEnv *, jobject);

/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    _stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_JNIPBFWrapper__1stop
  (JNIEnv *, jobject);

/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    _zoom
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_JNIPBFWrapper__1zoom
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    _move
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_JNIPBFWrapper__1move
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    _rotate
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fub_pbf_JNIPBFWrapper__1rotate
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     de_fub_pbf_JNIPBFWrapper
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_fub_pbf_JNIPBFWrapper_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
